# Generated by Django 5.0.6 on 2024-05-29 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'permissions': [('can_view_chat', 'Can view chat')]},
        ),
    ]
