# Generated by Django 5.0.6 on 2024-05-29 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_alter_chat_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'permissions': [('can_view_chat', 'Can view chat list')]},
        ),
    ]
