# Generated by Django 5.0.6 on 2024-06-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_logentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='action',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='author',
            field=models.CharField(max_length=255),
        ),
    ]
